# Generated by Django 5.2.17 on 2026-09-13 09:06

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.CharField(default=apps.people.models.generate_dev_id, max_length=255, primary_key=True, serialize=False),
        ),
    ]
