# Generated by Django 5.2.17 on 2026-09-10 05:22

import apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.CharField(default=apps.integrations.models.generate_int_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('system', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='Not Started', max_length=64)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('owner_id', models.CharField(blank=True, default='', max_length=64)),
                ('frequency', models.CharField(blank=True, default='', max_length=255)),
                ('data_objects', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
