# Generated by Django 5.2.17 on 2026-09-13 13:20

import apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('people', '0002_alter_developer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='id',
            field=models.CharField(default=apps.integrations.models.generate_int_id, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integration',
            name='owner_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='integration',
            name='status',
            field=models.CharField(default='Not Started', max_length=255),
        ),
        migrations.CreateModel(
            name='NAR',
            fields=[
                ('id', models.CharField(default=apps.integrations.models.generate_nar_id, max_length=255, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('status', models.CharField(default='Draft', max_length=255)),
                ('request_date', models.CharField(blank=True, default='', max_length=255)),
                ('end_date', models.CharField(blank=True, default='', max_length=255)),
                ('warning_days', models.IntegerField(default=30)),
                ('mail_subject', models.CharField(blank=True, default='', max_length=255)),
                ('requester', models.CharField(blank=True, default='', max_length=255)),
                ('approval_reference', models.CharField(blank=True, default='', max_length=255)),
                ('access_scope', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_ids', models.ManyToManyField(blank=True, related_name='nars', to='integrations.integration')),
                ('owner_ids', models.ManyToManyField(blank=True, related_name='nars', to='people.developer')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
