# Generated by Django 5.2.17 on 2026-09-10 05:22

import apps.gaps.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapClassification',
            fields=[
                ('id', models.CharField(default=apps.gaps.models.generate_gclass_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.CharField(default=apps.gaps.models.generate_gap_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Open', max_length=64)),
                ('priority', models.CharField(default='Medium', max_length=64)),
                ('due_date', models.CharField(blank=True, default='', max_length=64)),
                ('dependency', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('owner_ids', models.ManyToManyField(blank=True, related_name='gaps', to='people.developer')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaps', to='gaps.gapclassification')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
