# Generated by Django 5.2.17 on 2026-09-13 09:06

import apps.gaps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='due_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gap',
            name='id',
            field=models.CharField(default=apps.gaps.models.generate_gap_id, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gap',
            name='priority',
            field=models.CharField(default='Medium', max_length=255),
        ),
        migrations.AlterField(
            model_name='gap',
            name='status',
            field=models.CharField(default='Open', max_length=255),
        ),
        migrations.AlterField(
            model_name='gapclassification',
            name='id',
            field=models.CharField(default=apps.gaps.models.generate_gclass_id, max_length=255, primary_key=True, serialize=False),
        ),
    ]
