# Generated by Django 5.2.17 on 2026-09-10 05:22

import apps.portfolio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaps', '0001_initial'),
        ('integrations', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.CharField(default=apps.portfolio.models.generate_dom_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=apps.portfolio.models.generate_cat_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portfolio.domain')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.CharField(default=apps.portfolio.models.generate_uc_id, max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('business_value', models.TextField(blank=True, default='')),
                ('outputs', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Not Assessed', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='portfolio.category')),
                ('developer_ids', models.ManyToManyField(blank=True, related_name='use_cases', to='people.developer')),
                ('gap_ids', models.ManyToManyField(blank=True, related_name='use_cases', to='gaps.gap')),
                ('integration_ids', models.ManyToManyField(blank=True, related_name='use_cases', to='integrations.integration')),
            ],
            options={
                'ordering': ['reference', 'name'],
            },
        ),
    ]
