# Generated by Django 5.2.17 on 2026-09-13 13:20

import apps.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integration_id_alter_integration_owner_id_and_more'),
        ('people', '0002_alter_developer_id'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=apps.portfolio.models.generate_cat_id, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.CharField(default=apps.portfolio.models.generate_dom_id, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='id',
            field=models.CharField(default=apps.portfolio.models.generate_uc_id, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='status',
            field=models.CharField(default='Not Assessed', max_length=255),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.CharField(default=apps.portfolio.models.generate_pipe_id, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(default='Batch', max_length=255)),
                ('status', models.CharField(default='Planned', max_length=255)),
                ('server', models.CharField(blank=True, default='', max_length=255)),
                ('server_url', models.CharField(blank=True, default='', max_length=255)),
                ('environment', models.CharField(default='Development', max_length=255)),
                ('schedule', models.CharField(blank=True, default='', max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=255)),
                ('repository_url', models.CharField(blank=True, default='', max_length=255)),
                ('pipeline_path', models.CharField(blank=True, default='', max_length=255)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_ids', models.ManyToManyField(blank=True, related_name='pipelines', to='integrations.integration')),
                ('owner_ids', models.ManyToManyField(blank=True, related_name='pipelines', to='people.developer')),
                ('use_case_ids', models.ManyToManyField(blank=True, related_name='pipelines', to='portfolio.usecase')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
